# Generated by Django 3.1.6 on 2021-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210331_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_user',
            new_name='subscribers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='follow',
            name='follow_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
