# Generated by Django 3.1.6 on 2021-04-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210404_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='follow',
            name='subscriber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
