export const GET_NOTIFICATIONS_REQ = "GET_NOTIFICATIONS_REQ";
export const GET_NOTIFICATIONS_RES = "GET_NOTIFICATIONS_RES";
export const GET_NOTIFICATIONS_ERR = "GET_NOTIFICATIONS_ERR";

export const SHOW_IMPORTANT_NOTIFICATION_ALERT = "SHOW_IMPORTANT_NOTIFICATION_ALERT";
export const HIDDEN_IMPORTANT_NOTIFICATION_ALERT = "HIDDEN_IMPORTANT_NOTIFICATION_ALERT";

export const SHOW_SUCCESS_ALERT = "SHOW_SUCCESS_ALERT";
export const HIDDEN_SUCCESS_ALERT = "HIDDEN_SUCCESS_ALERT";

export const SHOW_CHECK_MAIL_ALERT = "SHOW_CHECK_MAIL_ALERT";
export const HIDE_CHECK_MAIL_ALERT = "HIDE_CHECK_MAIL_ALERT";

export const SHOW_ERROR_ALERT = "SHOW_ERROR_ALERT";
export const HIDE_ERROR_ALERT = "HIDE_ERROR_ALERT";
